version: '3.8'

services:
  db:
    container_name: db-ticket-service
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
    env_file:
      - .env
    ports:
      - "5432:5432"