version: '3.8'

services:
  db:
    container_name: db-ticket-service
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - service-dependencies

  rabbitmq:
    image: rabbitmq:3.6.14-management
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:5672"]
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBIT_USER}' 
      RABBITMQ_DEFAULT_PASS: '${RABBIT_PASS}'
    env_file:
      - .env
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    networks:
      - service-dependencies

networks:
  service-dependencies:
    driver: bridge
